import { Book } from "./type";

export const PLACEHOLDER_BOOKS: Book[] = [
  {
    id: "1",
    title: "Introduction to Algorithms",
    author: "Cormen, T.",
    callNumber: "QA76.6 .C662",
    category: "Computer Science",
    available: true,
    materialType: "Book",
    publicationDetails: "Cambridge, MA : MIT Press, 2009",
    year: 2009,
    rating: 5,
    coverUrl: "https://covers.openlibrary.org/b/id/240726-M.jpg",
  },
  {
    id: "2",
    title: "Noli Me Tangere",
    author: "Rizal, J.",
    callNumber: "PQ8686 .R5",
    category: "Philippine Literature",
    available: false,
    materialType: "Book",
    publicationDetails: "Manila : National Bookstore, 1996",
    year: 1996,
    rating: 5,
    coverUrl: "https://covers.openlibrary.org/b/id/8228691-M.jpg",
  },
  {
    id: "3",
    title: "A Brief History of Time",
    author: "Hawking, S.",
    callNumber: "QB981 .H377",
    category: "Science",
    available: true,
    materialType: "Book",
    publicationDetails: "New York : Bantam Books, 1998",
    year: 1998,
    rating: 4,
    coverUrl: "https://covers.openlibrary.org/b/id/240727-M.jpg",
  },
  // Extra Science books so list view can appear
  {
    id: "4",
    title: "The Selfish Gene",
    author: "Dawkins, R.",
    callNumber: "QH437 .D38",
    category: "Science",
    available: true,
    materialType: "Book",
    publicationDetails: "Oxford : Oxford University Press, 2006",
    year: 2006,
    rating: 5,
  },
  {
    id: "5",
    title: "Cosmos",
    author: "Sagan, C.",
    callNumber: "QB44.2 .S24",
    category: "Science",
    available: true,
    materialType: "Book",
    publicationDetails: "New York : Random House, 1980",
    year: 1980,
    rating: 5,
  },
  {
    id: "6",
    title: "The Origin of Species",
    author: "Darwin, C.",
    callNumber: "QH365 .O2",
    category: "Science",
    available: false,
    materialType: "Book",
    publicationDetails: "London : John Murray, 1859",
    year: 1859,
    rating: 5,
  },
  {
    id: "7",
    title: "Surely You're Joking, Mr. Feynman!",
    author: "Feynman, R.",
    callNumber: "QC16.F46 A3",
    category: "Science",
    available: true,
    materialType: "Book",
    publicationDetails: "New York : W.W. Norton, 1985",
    year: 1985,
    rating: 4,
  },
  {
    id: "8",
    title: "The Elegant Universe",
    author: "Greene, B.",
    callNumber: "QC794.6.S85 G75",
    category: "Science",
    available: true,
    materialType: "Book",
    publicationDetails: "New York : W.W. Norton, 2003",
    year: 2003,
    rating: 4,
  },
  {
    id: "9",
    title: "Silent Spring",
    author: "Carson, R.",
    callNumber: "QH545.P4 C38",
    category: "Science",
    available: true,
    materialType: "Book",
    publicationDetails: "Boston : Houghton Mifflin, 1962",
    year: 1962,
    rating: 5,
  },
  {
    id: "10",
    title: "The Double Helix",
    author: "Watson, J.",
    callNumber: "QH447 .W37",
    category: "Science",
    available: false,
    materialType: "Book",
    publicationDetails: "New York : Atheneum, 1968",
    year: 1968,
    rating: 4,
  },
];

export const ALPHABET_RANGES = ["A–F", "G–M", "N–S", "T–Z"];

export const SEARCH_SCOPES = [
  { value: "catalog", label: "Library catalog" },
  { value: "title", label: "Title" },
  { value: "author", label: "Author" },
  { value: "subject", label: "Subject" },
  { value: "isbn", label: "ISBN" },
  { value: "issn", label: "ISSN" },
  { value: "series", label: "Series" },
  { value: "call_number", label: "Call number" },
];